name: Convert TODOs to Issues

on:
  push:
    branches: [main]

jobs:
  todo-to-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Find TODOs and create issues
      uses: actions/github-script@v7
      with:
        script: |
          const { execSync } = require('child_process');
          const fs = require('fs');
          
          // Find all TODO comments in the codebase
          const todos = execSync('grep -r "TODO:" . --include="*.js" --include="*.ts" --include="*.tsx" --include="*.jsx" --include="*.md" || true', { encoding: 'utf8' });
          
          if (todos.trim()) {
            const todoLines = todos.trim().split('\n');
            
            for (const line of todoLines) {
              const match = line.match(/TODO:\s*(.+)/);
              if (match) {
                const todoText = match[1].trim();
                const fileName = line.split(':')[0];
                
                // Create issue
                await github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: `TODO: ${todoText}`,
                  body: `Found in: ${fileName}\n\nOriginal: ${line}`,
                  labels: ['todo', 'automated']
                });
              }
            }
          }

